import type { Data, Booking, User } from '../types';
import { seed, seatsFor } from '../data/seed';
const KEY='av_data_v2';
const API_BASE_URL=(import.meta.env.VITE_API_BASE_URL||'https://api.audienceverdict.in/api/v1').replace(/\/$/,'');
const memoryStore=new Map<string,unknown>();
export const storageService={
 read<T>(key:string,fallback:T):T {return (memoryStore.get(key) as T|undefined)??fallback;},
 write<T>(key:string,value:T){memoryStore.set(key,value);},
 remove(key:string){memoryStore.delete(key);}
};
export interface Repository<T extends {id:string}> {list():Promise<T[]>;get(id:string):Promise<T|null>;save(value:T):Promise<void>;delete(id:string):Promise<void>}
export const emptyData=():Data=>({movies:[],theatres:[],screens:[],shows:[],bookings:[],reviews:[],users:[],settings:{requireAdminConfirmation:false}});
function normaliseData(value:unknown):Data {const saved=value&&typeof value==='object'?value as Partial<Data>:{};return {movies:Array.isArray(saved.movies)?saved.movies:[],theatres:Array.isArray(saved.theatres)?saved.theatres:[],screens:Array.isArray(saved.screens)?saved.screens:[],shows:Array.isArray(saved.shows)?saved.shows:[],bookings:Array.isArray(saved.bookings)?saved.bookings:[],reviews:Array.isArray(saved.reviews)?saved.reviews:[],users:Array.isArray(saved.users)?saved.users:[],settings:{requireAdminConfirmation:Boolean((saved.settings as Data['settings']|undefined)?.requireAdminConfirmation)}};}
async function backendRequest<T>(path:string,init:RequestInit={}):Promise<T>{const token=localStorage.getItem('av_access_token')||sessionStorage.getItem('av_access_token');const url=`${API_BASE_URL}${path}`;const method=init.method||'GET';console.info(`[api request] ${method} ${url}`);const response=await fetch(url,{...init,headers:{Accept:'application/json',...(init.body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{}) ,...init.headers}});const responseText=await response.text();let body:any=null;try{body=responseText?JSON.parse(responseText):null;}catch{body=responseText||null;}if(response.status===401){localStorage.removeItem('av_access_token');sessionStorage.removeItem('av_access_token');window.dispatchEvent(new Event('av-auth-change'));}if(!response.ok){const message=typeof body==='string'?body:body?.message||body?.error||`Backend request failed (${response.status})`;console.error(`[api] ${method} ${url} failed (${response.status})`,body??response.statusText);throw new Error(`${message} [${method} ${url}, HTTP ${response.status}]`);}return body as T;}
export const database={read:():Data=>normaliseData(storageService.read<unknown>(KEY,emptyData())),write:(data:Data)=>{storageService.write(KEY,normaliseData(data));window.dispatchEvent(new Event('av-change'));},update:(fn:(data:Data)=>void)=>{const data=database.read();fn(data);database.write(data);},removeLocal:()=>storageService.remove(KEY)};
async function apiGet<T>(path:string):Promise<T>{return backendRequest<T>(path);}
async function apiWrite<T>(path:string, init:RequestInit):Promise<T>{return backendRequest<T>(path,init);}
let backendDataRequest:Promise<Data>|null=null;
export function loadBackendData(){if(backendDataRequest)return backendDataRequest;backendDataRequest=(async()=>{const results=await Promise.allSettled([apiGet<{content:Data['movies']}>(`/movies?size=200`),apiGet<{content:Data['theatres']}>(`/theatres?size=200`),apiGet<Data['shows']>('/shows'),apiGet<Data['reviews']>('/reviews')]);const failures=results.filter((result):result is PromiseRejectedResult=>result.status==='rejected');if(failures.length===results.length)throw new Error(`All catalogue requests failed. First error: ${failures[0].reason instanceof Error?failures[0].reason.message:String(failures[0].reason)}`);const [movieResult,theatreResult,showResult,reviewResult]=results;const current=database.read();const data={...current,movies:movieResult.status==='fulfilled'?movieResult.value.content:[],theatres:theatreResult.status==='fulfilled'?theatreResult.value.content:[],shows:showResult.status==='fulfilled'?showResult.value:[],reviews:reviewResult.status==='fulfilled'?reviewResult.value:[]};database.write(data);return data;})();return backendDataRequest;}
const loadedTheatreScreens=new Set<string>();
const pendingTheatreScreens=new Map<string,Promise<void>>();
export async function loadTheatreScreens(theatreIds:string[]){await Promise.all([...new Set(theatreIds)].filter(id=>!loadedTheatreScreens.has(id)).map(id=>{const pending=pendingTheatreScreens.get(id);if(pending)return pending;const request=apiGet<any[]>(`/theatres/${encodeURIComponent(id)}/screens`).then(screens=>{const normalized=screens.map(screen=>({...screen,seats:(screen.seats||[]).map((seat:any)=>({...seat,row:seat.row??seat.rowNumber,column:seat.column??seat.columnNumber}))}));database.update(data=>{data.screens=[...data.screens.filter(screen=>screen.theatreId!==id),...normalized];});loadedTheatreScreens.add(id);}).finally(()=>pendingTheatreScreens.delete(id));pendingTheatreScreens.set(id,request);return request;}));}
const remoteKeys=['movies','theatres','screens','shows','reviews'] as const;
export function repository<K extends Exclude<keyof Data,'settings'>>(key:K):Repository<Data[K][number]>{return {async list(){return database.read()[key] as Data[K][number][];},async get(id){return (database.read()[key] as Data[K][number][]).find(x=>x.id===id)||null;},async save(value){const list=database.read()[key] as any[];const exists=list.some(item=>item.id===value.id);if((remoteKeys as readonly string[]).includes(String(key))){let path=`/${String(key)}`;let payload:any=value;if(key==='screens'){path=exists?`/theatres/screens/${value.id}`:`/theatres/${(value as any).theatreId}/screens`;payload={id:value.id,theatreId:(value as any).theatreId,name:(value as any).name,number:(value as any).number,rows:(value as any).rows,seatsPerRow:(value as any).seatsPerRow,status:(value as any).status,layoutLocked:Boolean((value as any).layoutLocked),seats:((value as any).seats||[]).map((seat:any,index:number)=>({id:seat.id,label:seat.label||seat.id,category:seat.category||'REGULAR',color:seat.color||'#8B7A91',disabled:Boolean(seat.disabled),rowNumber:seat.row??seat.rowNumber??Math.floor(index/((value as any).seatsPerRow||1))+1,columnNumber:seat.column??seat.columnNumber??index%((value as any).seatsPerRow||1)+1}))};}else if(exists)path+=`/${value.id}`;if(key==='shows'){payload={...value,bookingOpens:(value as any).bookingOpens?new Date((value as any).bookingOpens).toISOString():null,bookingCloses:(value as any).bookingCloses?new Date((value as any).bookingCloses).toISOString():null,seatPrices:(value as any).seatPrices||{}};}const saved=await apiWrite<any>(path,{method:exists?'PUT':'POST',body:JSON.stringify(payload)});const normalized=key==='screens'?{...saved,seats:(saved?.seats||[]).map((seat:any)=>({...seat,row:seat.row??seat.rowNumber,column:seat.column??seat.columnNumber}))}:saved;database.update(data=>{const target=data[key] as any[];const i=target.findIndex(item=>item.id===value.id||item.id===normalized?.id);if(i<0)target.push(normalized||value);else target[i]=normalized||value;});return;}database.update(data=>{const target=data[key] as any[];const i=target.findIndex(item=>item.id===value.id);if(i<0)target.push(value);else target[i]=value;});},async delete(id){if((remoteKeys as readonly string[]).includes(String(key))){await apiWrite(`/${String(key)}/${id}`,{method:'DELETE'});}database.update(data=>{(data[key] as {id:string}[])=(data[key] as {id:string}[]).filter(x=>x.id!==id);});}};}
export const repositories={movies:repository('movies'),theatres:repository('theatres'),screens:repository('screens'),shows:repository('shows'),bookings:repository('bookings'),reviews:repository('reviews'),users:repository('users')};
export async function createScreen(theatreId:string, screen:any){ const payload={id:screen.id,theatreId,name:screen.name,number:screen.number,rows:screen.rows,seatsPerRow:screen.seatsPerRow,status:screen.status,layoutVersion:1,layoutLocked:false,seats:(screen.seats||[]).map((seat:any,index:number)=>({id:seat.id,label:seat.label||seat.id,category:seat.category||'REGULAR',color:seat.color||'#8B7A91',disabled:Boolean(seat.disabled),rowNumber:seat.row??seat.rowNumber??Math.floor(index/(screen.seatsPerRow||1))+1,columnNumber:seat.column??seat.columnNumber??index%(screen.seatsPerRow||1)+1}))}; return apiWrite<any>(`/theatres/${encodeURIComponent(theatreId)}/screens`,{method:'POST',body:JSON.stringify(payload)}); }
export interface PaymentService {pay(amount:number):Promise<{success:boolean;reference:string}>}
export const mockPaymentService:PaymentService={async pay(){await new Promise(r=>setTimeout(r,600));return {success:true,reference:`DEMO-${Date.now()}`};}};
export interface NotificationService {prepare(booking:Booking):Promise<string>}
export const mockNotificationService:NotificationService={async prepare(){return 'Demo: branded ticket email prepared. Nothing was sent.';}};
export {authService} from './auth';
export async function adminConfirmBooking(id:string){const saved=await apiWrite<any>(`/bookings/admin/${encodeURIComponent(id)}/confirm`,{method:'POST'});const normalized={...saved,snapshot:{movie:saved.movie,theatre:saved.theatre,screen:saved.screen,date:saved.date,time:saved.time,mobile:saved.mobile,email:saved.email}};database.update(data=>{const index=data.bookings.findIndex(item=>item.id===id);if(index>=0)data.bookings[index]={...data.bookings[index],...normalized};});return normalized;}
export async function adminCancelBooking(id:string,reason:string){return apiWrite<any>(`/bookings/admin/${encodeURIComponent(id)}/cancel`,{method:'POST',body:JSON.stringify({reason})});}
export async function adminMarkAttendance(id:string,attended=true){return apiWrite<any>(`/bookings/admin/${encodeURIComponent(id)}/attendance?attended=${attended}`,{method:'POST'});}
export async function listLayoutVersions(screenId:string){return apiGet<any[]>(`/theatres/screens/${screenId}/layout-versions`);}
export async function saveLayoutVersion(screenId:string,name:string,sourceVersionId?:string){const query=new URLSearchParams({name});if(sourceVersionId)query.set('sourceVersionId',sourceVersionId);return apiWrite<any>(`/theatres/screens/${screenId}/layout-versions?${query}`,{method:'POST'});}
export async function getLayoutVersion(screenId:string,versionId:string){return apiGet<any>(`/theatres/screens/${screenId}/layout-versions/${versionId}`);}
export async function saveLayoutSeats(screenId:string,versionId:string,seats:any[]){return apiWrite<any[]>(`/theatres/screens/${screenId}/layout-versions/${versionId}/seats`,{method:'PUT',body:JSON.stringify(seats.map(seat=>({label:seat.label||seat.id,rowNumber:seat.row??seat.rowNumber,columnNumber:seat.column??seat.columnNumber,category:seat.category,disabled:seat.disabled,color:seat.color})))});}
export async function publishLayoutVersion(screenId:string,versionId:string){return apiWrite<any>(`/theatres/screens/${screenId}/layout-versions/${versionId}/publish`,{method:'POST'});}
export async function getShowAvailability(showId:string){return apiGet<any>(`/shows/${showId}/availability`);}
export function validateBooking(data:Data,user:User,showId:string,seatIds:string[],now=new Date()){
 const show=data.shows.find(s=>s.id===showId);if(!show||show.status!=='OPEN'||new Date(`${show.date}T${show.startTime}`)<=now||(show.bookingOpens&&new Date(show.bookingOpens)>now)||(show.bookingCloses&&new Date(show.bookingCloses)<now))throw new Error('This show is unavailable for booking. Please choose another show.');
 const screen=data.screens.find(s=>s.id===show.screenId&&s.theatreId===show.theatreId&&s.status==='ACTIVE');if(!screen||!data.theatres.some(t=>t.id===show.theatreId&&t.status==='ACTIVE'))throw new Error('This theatre or screen is unavailable.');
 if(!seatIds.length||new Set(seatIds).size!==seatIds.length)throw new Error('Please select at least one available seat.');
 const active=data.bookings.filter(b=>b.showId===showId&&b.status!=='CANCELLED');
 const used=active.filter(b=>b.snapshot.mobile===user.mobile).reduce((n,b)=>n+b.ticketCount,0);
 if(used+seatIds.length>show.maxTicketsPerMobile)throw new Error(`You can book a maximum of ${show.maxTicketsPerMobile} tickets for this screening using the same mobile number. You already have ${used}.`);
 if(seatIds.some(id=>!screen.seats.some(s=>s.id===id&&!s.disabled)||active.some(b=>b.seatIds.includes(id))))throw new Error('A selected seat is already booked or unavailable. Please choose another seat.');
 return show;
}
export async function createBooking(user:User,showId:string,seatIds:string[],alternativeMobile?:string,termsAccepted=true){
 const backendBooking=await apiWrite<any>('/bookings',{method:'POST',body:JSON.stringify({showId,seatIds,alternativeMobile,termsAccepted})});
 const persisted:Booking={id:backendBooking.id,userId:backendBooking.userId,showId:backendBooking.showId,seatIds:backendBooking.seatIds,ticketCount:backendBooking.ticketCount,totalAmount:Number(backendBooking.totalAmount),status:backendBooking.status,confirmationStatus:backendBooking.confirmationStatus,createdAt:backendBooking.createdAt,attended:Boolean(backendBooking.attended),notification:backendBooking.notification||'',snapshot:{movie:backendBooking.movie,theatre:backendBooking.theatre,screen:backendBooking.screen,date:backendBooking.date,time:backendBooking.time,mobile:backendBooking.mobile,email:backendBooking.email}};
 database.update(data=>{data.bookings=[...data.bookings.filter(item=>item.id!==persisted.id),persisted];});
 return persisted;
 /* Local booking prototype retained below for reference; backend persistence is authoritative. */
 let show=validateBooking(database.read(),user,showId,seatIds);const amount=show.ticketType==='FREE'?0:show.ticketPrice*seatIds.length;
 if(amount){const result=await mockPaymentService.pay(amount);if(!result.success)throw new Error('Demo payment failed. Please try again.');}
 let booking!:Booking;
 database.update(data=>{show=validateBooking(data,user,showId,seatIds);if(amount!==(show.ticketType==='FREE'?0:show.ticketPrice*seatIds.length))throw new Error('The price changed. Please review your booking again.');const pending=show.requireAdminConfirmation||data.settings.requireAdminConfirmation;booking={id:`AV-${crypto.randomUUID().slice(0,8).toUpperCase()}`,userId:user.id,showId,seatIds,ticketCount:seatIds.length,totalAmount:amount,status:pending?'PENDING':'CONFIRMED',confirmationStatus:pending?'PENDING':'AUTO',createdAt:new Date().toISOString(),attended:false,notification:'Demo notifications prepared; no messages sent.',snapshot:{movie:data.movies.find(m=>m.id===show.movieId)?.title||'Movie',theatre:data.theatres.find(t=>t.id===show.theatreId)!.name,screen:data.screens.find(s=>s.id===show.screenId)!.name,date:show.date,time:show.startTime,mobile:user.mobile,email:user.email}};data.bookings.push(booking);});
 const notification=await mockNotificationService.prepare(booking);await repositories.bookings.save({...booking,notification});return booking;
}
export function removeEntity(key:'movies'|'theatres'|'screens'|'shows',id:string){database.update(d=>{const showIds=(predicate:(show:typeof d.shows[number])=>boolean)=>d.shows.filter(predicate).map(show=>show.id);const removeShows=(ids:string[])=>{d.bookings=d.bookings.filter(booking=>!ids.includes(booking.showId));d.shows=d.shows.filter(show=>!ids.includes(show.id));};if(key==='movies'){const ids=showIds(show=>show.movieId===id);removeShows(ids);d.reviews=d.reviews.filter(review=>review.movieId!==id);d.movies=d.movies.filter(movie=>movie.id!==id);return;}if(key==='theatres'){const ids=showIds(show=>show.theatreId===id);removeShows(ids);d.screens=d.screens.filter(screen=>screen.theatreId!==id);d.theatres=d.theatres.filter(theatre=>theatre.id!==id);return;}if(key==='screens'){const ids=showIds(show=>show.screenId===id);removeShows(ids);d.screens=d.screens.filter(screen=>screen.id!==id);return;}if(key==='shows'){removeShows([id]);}});}
export function embedUrl(raw:string):string|null {try{const u=new URL(raw);if(!['https:','http:'].includes(u.protocol))return null;const host=u.hostname.replace(/^www\./,'');if(host==='youtube.com'||host==='m.youtube.com'||host==='youtu.be'){const id=host==='youtu.be'?u.pathname.slice(1):u.searchParams.get('v')||u.pathname.split('/').pop();return id&&/^[\w-]{11}$/.test(id)?`https://www.youtube-nocookie.com/embed/${id}`:null;}if(host==='instagram.com'&&/^\/(p|reel)\/[\w-]+/.test(u.pathname))return `https://www.instagram.com${u.pathname.replace(/\/$/,'')}/embed`;if(host==='facebook.com')return `https://www.facebook.com/plugins/video.php?href=${encodeURIComponent(raw)}`;if(host==='drive.google.com'){const id=u.pathname.match(/\/file\/d\/([^/]+)/)?.[1]||u.searchParams.get('id');return id?`https://drive.google.com/file/d/${id}/preview`:null;}return null;}catch{return null;}}
export function socialUrl(raw:string){try{const u=new URL(raw);return u.protocol==='https:'&&['youtube.com','www.youtube.com','youtu.be','instagram.com','www.instagram.com','facebook.com','www.facebook.com','drive.google.com','x.com','twitter.com'].includes(u.hostname);}catch{return false;}}

export function ensureSampleCatalogue(){
 database.update(data=>{
  const addMovie=(movie:Data['movies'][number])=>{if(!data.movies.some(item=>item.id===movie.id||item.title.toLowerCase()===movie.title.toLowerCase()))data.movies.push(movie);};
  addMovie({id:'sample-sita-ramam',title:'Sita Ramam',posterUrl:'https://image.tmdb.org/t/p/w500/8hl5Ws8C8x9B3fXxV1FSh6APwzL.jpg',trailerUrl:'https://www.youtube.com/watch?v=Ljk6tGZ1l3A',description:'A letter from the past connects two strangers in a sweeping romance shaped by memory, duty, and courage.',genre:['Romance','Drama'],language:'Telugu',duration:163,releaseDate:'2022-08-05',certification:'U',director:'Hanu Raghavapudi',cast:['Dulquer Salmaan','Mrunal Thakur','Rashmika Mandanna'],production:'Vyjayanthi Movies',status:'ACTIVE'});
  addMovie({id:'sample-lucky-bhaskar',title:'Lucky Baskhar',posterUrl:'https://image.tmdb.org/t/p/w500/49U5j8kF9iOiNW2ENZYlV7oIT5Y.jpg',trailerUrl:'https://www.youtube.com/watch?v=0b6juT8e3Do',description:'An ordinary bank cashier is pulled into an extraordinary financial gamble that changes his family forever.',genre:['Crime','Drama','Thriller'],language:'Telugu',duration:148,releaseDate:'2024-10-31',certification:'UA',director:'Venky Atluri',cast:['Dulquer Salmaan','Meenakshi Chaudhary'],production:'Sithara Entertainments',status:'ACTIVE'});
  addMovie({id:'sample-kingdom',title:'Kingdom',posterUrl:'https://image.tmdb.org/t/p/w500/9JbAqCXPqFM6lRdkOngyH4QJbTJ.jpg',trailerUrl:'https://www.youtube.com/watch?v=dQw4w9WgXcQ',description:'A young man is drawn into a dangerous mission that tests loyalty, identity, and the cost of power.',genre:['Action','Drama'],language:'Telugu',duration:155,releaseDate:'2026-10-01',certification:'UA',director:'Gowtam Tinnanuri',cast:['Vijay Deverakonda','Bhagyashri Borse'],production:'Sithara Entertainments',status:'UPCOMING'});
  const ak=data.movies.find(item=>item.title.trim().toLowerCase()==='ak');const theatre=data.theatres[0];if(!ak||!theatre)return;
  const makeScreen=(id:string,name:string,number:number,rows:number,cols:number)=>{let screen=data.screens.find(item=>item.id===id);if(!screen){screen={id,theatreId:theatre.id,name,number,rows,seatsPerRow:cols,seats:seatsFor(rows,cols),status:'ACTIVE'};data.screens.push(screen);}return screen;};
  const screenA=makeScreen('sample-ak-screen-1','Ak Premiere Hall',21,7,11);const screenB=makeScreen('sample-ak-screen-2','Ak Luxe Screen',22,6,9);const day=(offset:number)=>{const value=new Date();value.setDate(value.getDate()+offset);return value.toISOString().slice(0,10);};
  const showData=[[screenA,day(1),'11:00','13:10',180],[screenA,day(1),'18:30','20:40',220],[screenB,day(2),'15:15','17:25',250],[screenB,day(2),'21:00','23:10',250]] as const;
  showData.forEach(([screen,date,startTime,endTime,price],index)=>{const id=`sample-ak-show-${index}`;if(!data.shows.some(item=>item.id===id))data.shows.push({id,movieId:ak.id,theatreId:theatre.id,screenId:screen.id,date,startTime,endTime,ticketType:'PAID',ticketPrice:price,maxTicketsPerMobile:4,requireAdminConfirmation:false,bookingOpens:'',bookingCloses:'',status:'OPEN'});});
 });
}



export async function createSeatHold(showId:string,seatIds:string[]){return apiWrite<any[]>(`/bookings/seat-holds`,{method:'POST',body:JSON.stringify({showId,seatIds})});}
export async function getSeatHolds(showId:string){return apiGet<any[]>(`/bookings/seat-holds?showId=${encodeURIComponent(showId)}`);}
export async function joinWaitingList(showId:string,requestedSeatsCount:number){return apiWrite<any>('/waiting-list',{method:'POST',body:JSON.stringify({showId,requestedSeatsCount})});}
export async function getWaitingList(){return apiGet<any[]>('/waiting-list');}
export async function leaveWaitingList(id:string){return apiWrite(`/waiting-list/${encodeURIComponent(id)}`,{method:'DELETE'});}
export async function claimWaitingList(id:string){return apiWrite<any>(`/waiting-list/${encodeURIComponent(id)}/claim`,{method:'POST'});}
export async function getNotifications(){return apiGet<any[]>('/notifications');}
export async function cancelBooking(id:string,seatIds?:string[]){return apiWrite<any>(`/bookings/${encodeURIComponent(id)}/cancel`,{method:'POST',body:JSON.stringify({seatIds})});}


export async function getAdminWaitingList(){return apiGet<any[]>('/waiting-list/admin');}
export async function sendAdminCampaign(payload:{target:'ALL_USERS'|'SHOW_BOOKERS'|'MOVIE_BOOKERS';subject:string;message:string;showId?:string;movieId?:string;status?:string;sortBy?:string;sortDirection?:string}){return apiWrite<{recipients:number;sent:number;skipped:number;channel:string}>('/notifications/admin/campaigns',{method:'POST',body:JSON.stringify(payload)});}
export async function sendShowReminder(showId:string){return apiWrite<{recipients:number;sent:number;skipped:number;channel:string}>(`/notifications/admin/shows/${encodeURIComponent(showId)}/reminder`,{method:'POST'});}
