import {useState} from 'react';
import {Check, Send} from 'lucide-react';
import {useApp} from '../context/AppContext';
import {sendAdminCampaign} from '../services/api';
import {Notice,SectionHeading} from '../components/Common';

export function AdminNotifications(){
 const {data}=useApp();const [target,setTarget]=useState<'ALL_USERS'|'SHOW_BOOKERS'|'MOVIE_BOOKERS'>('ALL_USERS');const [showId,setShowId]=useState('');const [movieId,setMovieId]=useState('');const [status,setStatus]=useState('');const [sortBy,setSortBy]=useState('name');const [sortDirection,setSortDirection]=useState('asc');const [subject,setSubject]=useState('A message from Audience Verdict');const [message,setMessage]=useState('Hi {{name}},\n\nWe have an update for you.');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [result,setResult]=useState('');
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');setResult('');try{const r=await sendAdminCampaign({target,subject,message,showId:target==='SHOW_BOOKERS'?showId:undefined,movieId:target==='MOVIE_BOOKERS'?movieId:undefined,status:target==='ALL_USERS'?undefined:status||undefined,sortBy,sortDirection});setResult(`Branded email sent to ${r.sent} of ${r.recipients} recipients${r.skipped?`; ${r.skipped} skipped because they do not have an email address`:''}.`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <div className="admin-content"><SectionHeading eyebrow="AUDIENCE MESSAGING" title="Notifications" description="Send personalized branded email updates to all users, movie audiences, or a specific show."/><form className="panel notification-composer" onSubmit={submit}><div className="form-grid"><label>Audience<select value={target} onChange={e=>setTarget(e.target.value as typeof target)}><option value="ALL_USERS">All registered users</option><option value="SHOW_BOOKERS">Users booked to a show</option><option value="MOVIE_BOOKERS">Users booked to a movie</option></select></label>{target==='SHOW_BOOKERS'&&<label>Show<select required value={showId} onChange={e=>setShowId(e.target.value)}><option value="">Choose show</option>{data.shows.map(s=><option key={s.id} value={s.id}>{data.movies.find(m=>m.id===s.movieId)?.title||'Movie'} · {s.date} · {s.startTime}</option>)}</select></label>}{target==='MOVIE_BOOKERS'&&<label>Movie<select required value={movieId} onChange={e=>setMovieId(e.target.value)}><option value="">Choose movie</option>{data.movies.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label>}{target!=='ALL_USERS'&&<label>Booking status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All non-cancelled bookings</option><option value="PENDING">Pending</option><option value="CONFIRMED">Confirmed</option></select></label>}<label>Sort recipients<select value={sortBy} onChange={e=>setSortBy(e.target.value)}><option value="name">Name</option><option value="email">Email</option><option value="mobile">Mobile</option><option value="joined">Registration date</option></select></label><label>Order<select value={sortDirection} onChange={e=>setSortDirection(e.target.value)}><option value="asc">Ascending</option><option value="desc">Descending</option></select></label></div><label>Subject<input maxLength={120} required value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>Message<textarea rows={8} maxLength={5000} required value={message} onChange={e=>setMessage(e.target.value)}/></label><div className="template-help"><strong>Personalization options</strong><span>{'{{name}}'} · {'{{email}}'} · {'{{mobile}}'} · {'{{movie}}'} · {'{{show_date}}'} · {'{{show_time}}'} · {'{{booking_id}}'}</span><small>For all users, show and booking details are empty when the recipient has no matching booking.</small></div>{error&&<Notice error>{error}</Notice>}{result&&<Notice>{result}</Notice>}<button className="button" disabled={busy}>{busy?'Sending…':'Send notification'} {busy?<Send size={16}/>:<Check size={16}/>}</button></form></div>;
}
