import {useState,type ReactNode} from 'react';
import {Link,NavLink,Outlet,useLocation} from 'react-router-dom';
import {ArrowUpRight,ArrowRight,Menu,X,MapPin,Ticket,Star,Play,LogOut,Clapperboard} from 'lucide-react';
import {useApp} from '../context/AppContext';
import {authService,embedUrl} from '../services/api';
import type {Movie,Review} from '../types';
export const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
export const date=(s:string)=>new Date(`${s.slice(0,10)}T12:00:00`).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'});
export function Logo(){return <Link to="/" className="logo"><span className="monogram">A<span>V</span><i/></span><span>AUDIENCE<br/>VERDICT<span className="logo-dot">.</span></span></Link>}
export function Layout(){const {user,admin}=useApp();const [open,setOpen]=useState(false);const location=useLocation();return <><header className="site-header"><div className="nav-wrap"><Logo/><nav className={open?'open':''} aria-label="Main navigation" onClick={()=>setOpen(false)}><NavLink to="/" end>Home</NavLink><NavLink to="/movies">Movies</NavLink><NavLink to="/audience-verdict">Audience Verdict</NavLink><NavLink to="/reviews">Reviews</NavLink><NavLink to="/about">About</NavLink>{user&&<NavLink to="/my-bookings">My Bookings</NavLink>}</nav><div className="nav-actions"><span className="location"><MapPin size={15}/> Hyderabad</span>{user?<Link className="button small" to="/profile">{user.name.split(' ')[0]}</Link>:<Link className="button small" to="/login">Login <ArrowUpRight size={15}/></Link>}<button className="icon-button mobile-menu" aria-label="Toggle navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div></header><main key={location.pathname}><Outlet/></main><footer><div className="footer-top"><Logo/><p>Great movies start conversations.<br/>This is where yours begins.</p><div><Link to="/movies">Explore movies</Link><Link to="/reviews">Audience reviews</Link><Link to={admin?'/admin':'/login?admin=1'}>Admin portal <ArrowUpRight size={13}/></Link></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} AV Audience Verdict</span><span>Made for the love of cinema.</span><span className="demo-label">Frontend demo · No real payments or messages</span></div></footer></>}
export function SectionHeading({eyebrow,title,description,link,to}:{eyebrow?:string;title:string;description?:string;link?:string;to?:string}){return <div className="section-heading"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h2>{title}</h2>{description&&<p>{description}</p>}</div>{to&&<Link className="text-link" to={to}>{link||'View all'} <ArrowRight size={17}/></Link>}</div>}
export function Poster({movie,className=''}:{movie:Movie;className?:string}){return <img className={className} src={movie.posterUrl} alt={`${movie.title} poster`} loading="lazy" onError={e=>{e.currentTarget.style.opacity='.15';}}/>}
export function MovieCard({movie}:{movie:Movie}){const {data}=useApp();const reviews=data.reviews.filter(r=>r.movieId===movie.id&&r.status==='APPROVED'&&r.rating>0);const rating=reviews.length?(reviews.reduce((a,r)=>a+r.rating,0)/reviews.length).toFixed(1):null;return <Link to={`/movie/${movie.id}`} className="movie-card"><div className="poster-wrap"><Poster movie={movie}/><span className={`poster-badge ${movie.status==='UPCOMING'?'upcoming':''}`}><span/>{movie.status==='UPCOMING'?'Coming soon':'Now screening'}</span><div className="poster-bottom">{rating?<span><Star size={14} fill="currentColor"/> {rating}<small> / 5 audience</small></span>:<span>Be the first to weigh in</span>}<span className="round-arrow"><ArrowUpRight size={19}/></span></div></div><h3>{movie.title}</h3><p>{movie.language} <span>·</span> {movie.genre.join(' / ')}</p><div className="card-detail">{movie.duration} min <span>·</span> {date(movie.releaseDate)}</div></Link>}
export function Empty({title,children}:{title:string;children?:ReactNode}){return <div className="empty"><Clapperboard size={36}/><h3>{title}</h3>{children}</div>}
export function Notice({children,error=false}:{children:ReactNode;error?:boolean}){return <div role={error?'alert':'status'} className={`notice ${error?'error':''}`}>{children}</div>}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){return <div className="modal-shade" onClick={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label={title} onClick={e=>e.stopPropagation()}><div className="modal-heading"><h2>{title}</h2><button autoFocus className="icon-button" onClick={onClose} aria-label="Close dialog"><X/></button></div>{children}</section></div>}
export function Video({url,title}:{url:string;title:string}){const embed=embedUrl(url);return embed?<iframe className="video-frame" src={embed} title={title} loading="lazy" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/>:<div className="panel"><p>This platform does not provide a supported embedded player.</p><a href={url} target="_blank" rel="noreferrer" className="text-link">Watch on the original platform <ArrowUpRight size={16}/></a></div>}
export function ReviewCard({review}:{review:Review}){const {data}=useApp();const [play,setPlay]=useState(false);const movie=data.movies.find(m=>m.id===review.movieId);return <article className={`review-card ${review.videoUrl?'video-review':''}`}>{review.videoUrl?<><button className="video-cover" onClick={()=>setPlay(true)} style={{backgroundImage:`linear-gradient(0deg,#0009,#0002),url("${review.thumbnail||movie?.posterUrl}")`}}><span className="play-circle"><Play size={22} fill="currentColor"/></span><span className="video-source">{review.platform} · EXTERNAL VIDEO</span></button>{play&&<Modal title={review.title} onClose={()=>setPlay(false)}><Video url={review.videoUrl} title={review.title}/><p className="muted">External content may require platform cookies or sign-in.</p></Modal>}</>:<div className="stars">{Array.from({length:5},(_,i)=><Star key={i} size={14} fill={i<review.rating?'currentColor':'none'}/>)}</div>}<div className="review-content"><div className="review-movie">{movie?.title||'Audience review'} {review.isHighlighted&&<span>FEATURED</span>}</div><h3>{review.title}</h3><p>{review.text}</p><div className="review-author"><span className="avatar">{review.author.slice(0,1)}</span><div><strong>{review.author}</strong><small>{date(review.createdAt)}</small></div><span className="review-mark">“</span></div></div></article>}
export function Logout(){return <button className="button secondary" onClick={()=>authService.logout()}><LogOut size={17}/> Logout</button>}
export function TicketIcon(){return <Ticket size={18}/>}
