import {useEffect} from 'react';
import {BrowserRouter, Link, Route, Routes, useLocation} from 'react-router-dom';
import {AppProvider} from './context/AppContext';
import {Empty, Layout} from './components/Common';
import {Home, Movies, MovieDetails, About} from './pages/Public';
import {ProtectedRoute, Login, Bookings, DigitalTicket, Profile, Reviews, MyWaitingList} from './pages/User';
import {BookMyShow} from './pages/BookMyShow';
import {VenueSetup} from './pages/VenueSetup';
import {ScreenWorkspace} from './pages/ScreenWorkspace';
import {AdminLayout, Dashboard, Manage, MovieEditor, AdminBookings, Audience, AdminSettings, ShowWorkspace, AdminWaitingList} from './pages/Admin';
import {AdminNotifications} from './pages/AdminNotifications';
function ScrollTop(){const {pathname}=useLocation();useEffect(()=>{window.scrollTo(0,0);},[pathname]);return null;}
export default function App(){return <AppProvider><BrowserRouter><ScrollTop/><Routes><Route element={<Layout/>}><Route index element={<Home/>}/><Route path="movies" element={<Movies/>}/><Route path="movie/:movieId" element={<MovieDetails/>}/><Route path="movie/:movieId/book" element={<ProtectedRoute><BookMyShow/></ProtectedRoute>}/><Route path="movie/:movieId/reviews" element={<Reviews/>}/><Route path="reviews" element={<Reviews/>}/><Route path="audience-verdict" element={<About/>}/><Route path="about" element={<About/>}/><Route path="login" element={<Login/>}/><Route path="verify-otp" element={<Login/>}/><Route path="my-bookings" element={<ProtectedRoute><Bookings/></ProtectedRoute>}/><Route path="my-waitlist" element={<ProtectedRoute><MyWaitingList/></ProtectedRoute>}/><Route path="booking/:bookingId" element={<ProtectedRoute><DigitalTicket/></ProtectedRoute>}/><Route path="profile" element={<ProtectedRoute><Profile/></ProtectedRoute>}/><Route path="*" element={<Empty title="This page is out of frame."><Link to="/" className="button">Back home</Link></Empty>}/></Route><Route path="admin" element={<ProtectedRoute adminOnly><AdminLayout/></ProtectedRoute>}><Route index element={<Dashboard/>}/><Route path="venues" element={<VenueSetup/>}/><Route path="venues/:venueId/screens/:screenId" element={<ScreenWorkspace/>}/><Route path="shows/:showId" element={<ShowWorkspace/>}/>{['movies','theatres','screens','shows','reviews'].map(path=><Route key={path} path={path} element={<Manage key={path}/>}/>)}<Route path="movies/new" element={<MovieEditor/>}/><Route path="movies/:id/edit" element={<MovieEditor/>}/><Route path="bookings" element={<AdminBookings/>}/><Route path="waiting-list" element={<AdminWaitingList/>}/><Route path="notifications" element={<AdminNotifications/>}/><Route path="audience" element={<Audience/>}/><Route path="settings" element={<AdminSettings/>}/></Route></Routes></BrowserRouter></AppProvider>}
